### ISSUE TITLE
추가 수정 요구사항 

### ISSUE THREAD

**Issue by zhtcks** [daangn-daangn/daangn-server#102]
- ~~물품 상세  조회 API에서 seller_id 필드 추가 하기~~
  - 판매자 닉네임만 준다 그래서 id가 없으면 로그인한 사람이랑 판매자가 같은지를 체크할 수 없어서
- ~~물품 리스트 조회 API에서 썸네일 URL key값을 `image_url`에서 `thumb_nail_image`로 변경하기~~
- ~~Product Domain에서 `name` 필드 제거하기~~
- ~~물품 상세 조회 API에서 `현재 로그인한 사용자의 찜하기 여부 판단`을 알 수 있는 장치 필요~~
  - 좋아요 여부를 판단하는 boolean 필드를 내려주거나
  - 어떤 사용자들이 좋아요를 눌렀는지 유저 id를 배열로 내려주면 좋을 것 같다.

**Comment by cotchan** [comment]
- #104
