### ISSUE TITLE
프로젝트 구조 분리

### ISSUE THREAD

**Issue by cotchan** [daangn-daangn/daangn-server#21]
api-server, chatting-server에서 common entity 사용할 수 있도록 수정

**Comment by zhtcks** [comment]
# 작업 내용

- #23 

## 1. 프로젝트 구조 변경

- api-server, chatting-server에서 rdb(Mysql), mongodb 모두 사용할 수 있도록 수정
  - rdb, mongodb와 관련된 코드(entity, document, repository)를 common 모듈(라이브러리)로 분리
  - 즉, api-server, chatting-server에서 common 모듈(라이브러리)을 사용하는 방식으로 수정
  - api-server, chatting-server에는 service, controller 존재
  - common 모듈에는 entity, document, repository만 존재
- 프로젝트 구조를 변경하면서 db 설정은 별도로 분리하고 나머지 설정만 `application.yml`에서 관리하도록 수정

![스크린샷 2022-05-05 오전 12 05 05](https://user-images.githubusercontent.com/75410527/166711301-daa48ce9-a258-47ae-b742-f36a27eaeca3.png)

## 2. DB(mysql, mongodb) 서버 생성

- 프로젝트 구조 변경 작업해보니 과금때문에 계속 local DB만 쓰다가는 나중에 DB 설정 때문에 번거로워질 같아서 그냥 DB 서버 생성해놨습니다.
- 다른 의견있으시면 말씀해주면 감사하겠습니다.
